tiygiftexchange/tiygiftexchange/Models/Gift.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace tiygiftexchange.Models
{
    public class Gift
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public string GiftHint { get; set; }
        public string ColorWrappingPaper { get; set; }
        public int? Height { get; set; }
        public int? Width { get; set; }
        public int? Depth { get; set; }
        public int? Weight { get; set; }
        public bool? IsOpened { get; set; }


        public Gift() { }

        public Gift(SqlDataReader reader)
        {
            this.Id = (int)reader["Id"];
            this.Contents = reader["Contents"].ToString();
            this.GiftHint = reader["GiftHint"].ToString();
            this.ColorWrappingPaper = reader["ColorWrappingPaper"].ToString();
            this.Height = reader["Height"] as int?;
            this.Width = reader["Width"] as int?;
            this.Depth = reader["Depth"] as int?;
            this.Weight = reader["Weight"] as int?;
            this.IsOpened = reader["IsOpened"] as bool?;

        }
    }
}

tiygiftexchange/tiygiftexchange/Controllers/GiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tiygiftexchange.Models;
using tiygiftexchange.Services;

namespace tiygiftexchange.Controllers
{
    public class GiftController : Controller
    {
        // GET: Gift
        public ActionResult Index()
        {
            //get all gifts
            var gifts = new GiftServices().GetAllGifts();
            //pass them to the view
            return View(gifts);
        } 
        //this is my get for my putpost. 
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //create new gift
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
           
            var newGift = new Gift {
                Contents = collection["Contents"],
                GiftHint = collection["GiftHint"],
                ColorWrappingPaper = collection["ColorWrappingPaper"],
                Height = int.Parse(collection["Height"]),
                Width = int.Parse(collection["Width"]),
                Depth = int.Parse(collection["Depth"]),
                Weight = int.Parse(collection["Weight"]),
                IsOpened = bool.Parse(collection["IsOpened"])

            };
            // TODO: Put into db
            new GiftServices().AddGift(newGift);
            return RedirectToAction("Index");
        }

        //get gift for edit. 
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var gift = new GiftServices().GetGift(id);
            return View(gift);
        }

        //edit gift
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var updatedGift = new Gift
            {
                Contents = collection["Contents"],
                GiftHint = collection["GiftHint"],
                ColorWrappingPaper = collection["ColorWrappingPaper"],
                Height = int.Parse(collection["Height"]),
                Width = int.Parse(collection["Width"]),
                Depth = int.Parse(collection["Depth"]),
                Weight = int.Parse(collection["Weight"]),
                IsOpened = bool.Parse(collection["IsOpened"]),
                Id = id
            };
            //save to database
            //display correct page. 
            new GiftServices().EditGift(updatedGift, id);
            return RedirectToAction("Index");
        }

        //get gift for delete. 
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var gift = new GiftServices().GetGift(id);
            return View(gift);
        }

        //delete gift
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            // TODO: fix this
            new GiftServices().DeleteGift(id);
            return RedirectToAction("Index");
        }

        //get the gift to open
        [HttpGet]
        public ActionResult Open(int id)
        {
            var gift = new GiftServices().GetGift(id);
            return View(gift);
        }

        //post for open gift
        [HttpPost]
        public ActionResult Open(int id, FormCollection collection)
        {
            new GiftServices().OpenGift(id);
            return RedirectToAction("Index");
        }
    }
    
}

tiygiftexchange/tiygiftexchange/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tiygiftexchange.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

tiygiftexchange/tiygiftexchange/Views/Gift/Create.cshtml
@model tiygiftexchange.Models.Gift

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gift</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contents, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contents, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiftHint, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiftHint, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiftHint, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColorWrappingPaper, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ColorWrappingPaper, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ColorWrappingPaper, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Width, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Depth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Depth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Depth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsOpened, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsOpened, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsOpened, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

tiygiftexchange/tiygiftexchange/Views/Gift/Delete.cshtml
@model tiygiftexchange.Models.Gift

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Gift</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Contents)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contents)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiftHint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiftHint)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ColorWrappingPaper)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ColorWrappingPaper)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Depth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Depth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsOpened)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsOpened)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

tiygiftexchange/tiygiftexchange/Views/Gift/Edit.cshtml
@model tiygiftexchange.Models.Gift

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gift</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contents, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contents, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiftHint, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiftHint, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiftHint, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColorWrappingPaper, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ColorWrappingPaper, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ColorWrappingPaper, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Width, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Depth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Depth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Depth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsOpened, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsOpened, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsOpened, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

tiygiftexchange/tiygiftexchange/Views/Gift/Index.cshtml
@model IEnumerable<tiygiftexchange.Models.Gift>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Contents)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GiftHint)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ColorWrappingPaper)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Width)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Depth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @if (item.IsOpened.GetValueOrDefault())
            {
                @Html.DisplayFor(modelItem => item.Contents)
            }
            else
            {
                <span>*****NOT OPENED*****</span>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GiftHint)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ColorWrappingPaper)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Height)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Width)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Depth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }) |
            @Html.ActionLink("Open Gift", "Open", new { id = item.Id })
        </td>
    </tr>
}

</table>

tiygiftexchange/tiygiftexchange/Views/Gift/Open.cshtml
@model tiygiftexchange.Models.Gift

@{
    ViewBag.Title = "Open";
}

<h2>Open Gift</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Are you sure you want to open this GIFT????</h4>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Open" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

tiygiftexchange/tiygiftexchange/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

tiygiftexchange/tiygiftexchange/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

tiygiftexchange/tiygiftexchange/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <div class="presentsWordsLeft">
        <h1>Who wants presents?</h1>
        <p class="lead">Here is some text to fill in some space so people can read something before they click the button to get some presents!</p>
    </div>
    <div class="giftButton">
        <h5>@Html.ActionLink("Gift List", "Index", "Gift", null, new { @class = "btn btn-default" })</h5>
    </div>
    <div class="elephantPic">
        <img src="http://www.clker.com/cliparts/e/s/R/k/3/4/white-elephant-with-santa-hat-md.png" alt="Elephant Man" />
    </div>
</div>



<div class="row">
    <div class="col-md-4">
        <h2 class="Home-p">Gift buying tips.</h2>
        <p>
            Don't get people garbage...no one likes garbage.
        </p>
        <p>@Html.ActionLink("Gift List", "Index", "Gift", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2 class="Home-p">Got a bad gift?</h2>
        <p>Easy solution...regift it at next years White Elephant.</p>
        <p>@Html.ActionLink("Gift List", "Index", "Gift", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2 class="Home-p">Awesome gift?</h2>
        <p>Make sure to show it off to everyone...especially those with poor gifts.</p>
        <p>@Html.ActionLink("Gift List", "Index", "Gift", null, new { @class = "btn btn-default" })</p>
    </div>

</div>
<img class="img-responsive center-block" sytle="margin-top: 20px" src="https://static.gyft.com/wp-content/uploads/2015/12/White-Elephant-Blog-Header-1200x500.png?9c5846" alt="Christmas Time" />

tiygiftexchange/tiygiftexchange/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - White Elephant</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("!!The Iron Yard White Elephant Extravaganza!!", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Gift List", "Index", "Gift")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TIY White Elephant</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>